ALTER TABLE rejected_signals
  MODIFY COLUMN reject_stage ENUM(
    'FUNDAMENTAL_FILTER',
    'SENTIMENT_FILTER',
    'VWAP_FILTER',
    'PCR_FILTER',
    'SECTOR_GATE',
    'CONFIDENCE_GATE',
    'RR_GATE',
    'LIQUIDITY_GATE',
    'MERGED_RISK_ZERO',
    'ACTIVE_CAP',
    'POSITION_SIZING',
    'DUPLICATE'
  ) NOT NULL;
