ALTER TABLE paper_trades
  MODIFY COLUMN exit_reason ENUM('TARGET_HIT','SL_HIT','EXPIRED','MANUAL','EXPIRED_PENALIZED');

ALTER TABLE signal_outcomes
  MODIFY COLUMN outcome ENUM('TARGET_HIT','SL_HIT','EXPIRED','EXPIRED_PENALIZED') NOT NULL;
